Introduce page header
gokerlek/goker-blog pull request #24
Opened 2021-02-28 20:17 UTC by gokerlek

"pageheader" folders created. day1 day2 and day3 have new headers.

2021-03-05 07:30 UTC, onerzafer requested changes

2021-03-05 07:30 UTC, onerzafer commented on src/components/pageHeader/pageHeader.js
> +import './pageHeader.css'
naming convention for files is kebabcase so page-header.css and page-header.js

2021-03-05 07:30 UTC, onerzafer commented on src/pages/day1.js
> +        <PageHeader>LOGIN TO REACT</PageHeader>
As a title "React: very first steps" would be more meaningful

2021-03-05 07:30 UTC, onerzafer commented on src/pages/day2.js
> +        <PageHeader>CREATING THE BASIC BUILDING STONES OF THE INTERNET SITE</PageHeader>
"CREATING THE BASIC BUILDING STONES OF THE INTERNET SITE" -> CREATING THE BASIC BUILDING STONES OF A REACT WEBSITE

2021-03-05 07:30 UTC, onerzafer commented on src/components/pageHeader/pageHeader.js
> +    return <div className="pageHeader">
tag can be h1 instead of div

2021-03-06 20:24 UTC, onerzafer commented on src/components/page-header/page-header.js
> +import './page-header.css'
Where is this file?

2021-03-06 21:27 UTC, gokerlek commented on src/components/page-header/page-header.js
> +import './page-header.css'
file deleted. it is not necessary

2021-03-06 22:07 UTC, onerzafer approved these changes

2021-03-07 08:52 UTC, merged