Contact me page
gokerlek/goker-blog pull request #25
Opened 2021-03-06 19:53 UTC by gokerlek

contact me page finished

2021-03-06 20:40 UTC, onerzafer requested changes

2021-03-06 20:40 UTC, onerzafer commented on src/components/image-wrapper/image-wrapper.js
> +export const ImageWrapper = ({ children }) => {
-As I can see the Image wrapper is used for icons an links. In general this is a good idea. But semantically the name is not suitable. How about a component name as IconWithLink?

Another optimizations would be not repeating the usage. To do so this component can be changed to this

```javascript
const IconWithLink = ({icon, link}) => {
const IconComponent = icon;
return <a href={link} className="icon-wapper"><IconComponent /></a>
}

```

Therefore the usage would be like

```javascript
<IconWithLink link="https://somelink.com" icon={FaIntagram} />
```
What do you think?

2021-03-06 20:40 UTC, onerzafer commented on src/pages/contact.js
> +        <p>+90 542 323 92 48</p>
No phone number online😉 and no email online

If someone would like to reach you they can use the platforms below

2021-03-06 22:11 UTC, onerzafer commented on src/components/icon-component/icon-with-link.css
> +    .icon-wapper img {
Are the icons img?

2021-03-07 08:49 UTC, gokerlek commented on src/components/icon-component/icon-with-link.css
> +    .icon-wapper img {
:D

2021-03-07 09:29 UTC, onerzafer approved these changes

2021-03-07 10:21 UTC, merged